from enum import Enum


class CatalogueStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


MAX_SLUG_LENGTH = 100
MAX_SKU_LENGTH = 64
MAX_NAME_LENGTH = 150
MAX_DESCRIPTION_LENGTH = 2000

PRICE_PRECISION = 12
PRICE_SCALE = 2
