from enum import Enum


class CatalogueStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


MAX_SKU_LENGTH = 64
MAX_NAME_LENGTH = 150
MAX_DESCRIPTION_LENGTH = 2000

PRICE_PRECISION = 12
PRICE_SCALE = 2

MAX_BRAND_LENGTH = 150

MAX_SHORT_DESCRIPTION_LENGTH = 500

MAX_SEO_TITLE_LENGTH = 200

MAX_SEO_DESCRIPTION_LENGTH = 500

MAX_IMAGE_URL_LENGTH = 2048
MAX_ALT_TEXT_LENGTH = 255