"""constrain user role and drop redundant tenant index

Revision ID: 018a1e9dbd22
Revises: d0721ebac024
Create Date: 2026-08-13 17:42:29.309184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018a1e9dbd22'
down_revision: Union[str, Sequence[str], None] = 'd0721ebac024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ix_users_tenant_id is a leading-column prefix of uq_users_tenant_email,
    # so Postgres can already serve tenant_id lookups from that index. Keeping
    # both costs an extra write per insert/update for no read benefit.
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')

    # `role` is a plain varchar; without this the database accepts any string,
    # including a typo or a role invented by a future code path.
    op.create_check_constraint(op.f('ck_users_role_valid'), 'users', "role IN ('PLATFORM_ADMIN', 'TENANT_ADMIN', 'STAFF', 'CUSTOMER')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_users_role_valid'), 'users', type_='check')
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
