"""shipping and tax settings, order tax amount

Two settings rows per tenant -- one flat delivery charge, one tax percentage --
and the column that records what tax an order actually paid.

`orders.tax_amount` is stored rather than derived, so changing a tenant's rate
tomorrow cannot rewrite what a customer was charged today. The total check
constraint is widened to include it.

Revision ID: 07b3782bd151
Revises: a46fa272fa9b
Create Date: 2026-08-28 22:17:56.735799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b3782bd151'
down_revision: Union[str, Sequence[str], None] = 'a46fa272fa9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('free_shipping_minimum', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('free_shipping_minimum IS NULL OR free_shipping_minimum >= 0', name=op.f('ck_shipping_settings_free_shipping_minimum_not_negative')),
    sa.CheckConstraint('shipping_amount >= 0', name=op.f('ck_shipping_settings_shipping_amount_not_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_shipping_settings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipping_settings')),
    sa.UniqueConstraint('tenant_id', name='uq_shipping_settings_tenant_id')
    )
    op.create_table('tax_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('tax_percentage >= 0 AND tax_percentage <= 100', name=op.f('ck_tax_settings_tax_percentage_in_range')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tax_settings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_settings')),
    sa.UniqueConstraint('tenant_id', name='uq_tax_settings_tenant_id')
    )
    # Added nullable, backfilled, then tightened: orders placed before tax
    # existed were charged none, and the model declares no server default.
    op.add_column('orders', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.execute("UPDATE orders SET tax_amount = 0 WHERE tax_amount IS NULL")
    op.alter_column('orders', 'tax_amount', nullable=False)

    # Widen the total to include tax. The old constraint has to go first --
    # with tax_amount backfilled to 0 both hold, but only one may be named.
    op.drop_constraint(op.f('ck_orders_total_is_subtotal_plus_shipping'), 'orders', type_='check')
    op.create_check_constraint(op.f('ck_orders_tax_not_negative'), 'orders', 'tax_amount >= 0')
    op.create_check_constraint(op.f('ck_orders_total_is_subtotal_plus_shipping_plus_tax'), 'orders', 'total_amount = subtotal + shipping_amount + tax_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_orders_total_is_subtotal_plus_shipping_plus_tax'), 'orders', type_='check')
    op.drop_constraint(op.f('ck_orders_tax_not_negative'), 'orders', type_='check')
    # Fold the tax back into the total before the narrower constraint returns,
    # otherwise every order that paid tax would violate it.
    op.execute("UPDATE orders SET total_amount = subtotal + shipping_amount")
    op.drop_column('orders', 'tax_amount')
    op.create_check_constraint(op.f('ck_orders_total_is_subtotal_plus_shipping'), 'orders', 'total_amount = (subtotal + shipping_amount)')
    op.drop_table('tax_settings')
    op.drop_table('shipping_settings')
    # ### end Alembic commands ###
