"""fix review fk set null bug

Revision ID: 1c2e5eb26f5c
Revises: 670d5eb85560
Create Date: 2026-09-02 06:19:22.021642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2e5eb26f5c'
down_revision: Union[str, Sequence[str], None] = '670d5eb85560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_tenant_order_orders'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_tenant_user_users'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_tenant_product_products'), 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_product_id_products'), 'reviews', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_reviews_user_id_users'), 'reviews', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_reviews_order_id_orders'), 'reviews', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_order_id_orders'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_user_id_users'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_product_id_products'), 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_tenant_product_products'), 'reviews', 'products', ['tenant_id', 'product_id'], ['tenant_id', 'id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_reviews_tenant_user_users'), 'reviews', 'users', ['tenant_id', 'user_id'], ['tenant_id', 'id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_reviews_tenant_order_orders'), 'reviews', 'orders', ['tenant_id', 'order_id'], ['tenant_id', 'id'], ondelete='SET NULL')
    # ### end Alembic commands ###
