"""add product gender attribute

Revision ID: 312bdf33cd6b
Revises: 8b02b8c9c826
Create Date: 2026-09-03 07:50:02.280541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312bdf33cd6b'
down_revision: Union[str, Sequence[str], None] = '8b02b8c9c826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('gender', sa.String(length=10), nullable=True))
    op.create_index('ix_products_tenant_id_gender', 'products', ['tenant_id', 'gender'], unique=False)
    op.create_check_constraint(op.f('ck_products_gender_valid'), 'products', "gender IS NULL OR gender IN ('MEN', 'WOMEN', 'UNISEX')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_products_gender_valid'), 'products', type_='check')
    op.drop_index('ix_products_tenant_id_gender', table_name='products')
    op.drop_column('products', 'gender')
    # ### end Alembic commands ###
