"""add coupons tables

Revision ID: 346e90ad9f8c
Revises: 07b3782bd151
Create Date: 2026-09-01 18:46:21.802422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '346e90ad9f8c'
down_revision: Union[str, Sequence[str], None] = '07b3782bd151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('per_customer_usage_limit', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("discount_type != 'PERCENTAGE' OR discount_value <= 100", name=op.f('ck_coupons_percentage_max_100')),
    sa.CheckConstraint("discount_type IN ('FIXED_AMOUNT', 'PERCENTAGE')", name=op.f('ck_coupons_discount_type_valid')),
    sa.CheckConstraint('discount_value > 0', name=op.f('ck_coupons_discount_value_positive')),
    sa.CheckConstraint('max_discount_amount IS NULL OR max_discount_amount >= 0', name=op.f('ck_coupons_max_discount_amount_not_negative')),
    sa.CheckConstraint('min_order_amount IS NULL OR min_order_amount >= 0', name=op.f('ck_coupons_min_order_amount_not_negative')),
    sa.CheckConstraint('per_customer_usage_limit IS NULL OR per_customer_usage_limit >= 0', name=op.f('ck_coupons_per_customer_usage_limit_not_negative')),
    sa.CheckConstraint('times_used >= 0', name=op.f('ck_coupons_times_used_not_negative')),
    sa.CheckConstraint('usage_limit IS NULL OR usage_limit >= 0', name=op.f('ck_coupons_usage_limit_not_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_coupons_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_coupons_tenant_id_code')
    )
    op.create_index(op.f('ix_coupons_tenant_id'), 'coupons', ['tenant_id'], unique=False)
    op.create_table('coupon_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_coupon_usages_discount_amount_not_negative')),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_coupon_usages_coupon_id_coupons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_coupon_usages_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_coupon_usages_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_coupon_usages_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_usages')),
    sa.UniqueConstraint('tenant_id', 'order_id', name='uq_coupon_usages_tenant_id_order_id')
    )
    op.create_index(op.f('ix_coupon_usages_coupon_id'), 'coupon_usages', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_customer_id'), 'coupon_usages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_coupon_usages_tenant_id'), 'coupon_usages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupon_usages_tenant_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_customer_id'), table_name='coupon_usages')
    op.drop_index(op.f('ix_coupon_usages_coupon_id'), table_name='coupon_usages')
    op.drop_table('coupon_usages')
    op.drop_index(op.f('ix_coupons_tenant_id'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
