"""add wishlist tables

Revision ID: 50a8b75ce593
Revises: 50a8b75ce593
Create Date: 2026-08-29 18:21:32.820375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a8b75ce593'
down_revision: Union[str, Sequence[str], None] = '07b3782bd151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'customer_id'], ['users.tenant_id', 'users.id'], name='fk_wishlists_tenant_customer_users', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_wishlists_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wishlists')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_wishlists_tenant_id_id')
    )
    op.create_index('uq_wishlists_one_per_customer', 'wishlists', ['tenant_id', 'customer_id'], unique=True)
    op.create_table('wishlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('wishlist_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'variant_id'], ['product_variants.tenant_id', 'product_variants.id'], name='fk_wishlist_items_tenant_variant_product_variants', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'wishlist_id'], ['wishlists.tenant_id', 'wishlists.id'], name='fk_wishlist_items_tenant_wishlist_wishlists', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_wishlist_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wishlist_items')),
    sa.UniqueConstraint('wishlist_id', 'variant_id', name='uq_wishlist_items_wishlist_variant')
    )
    op.create_index('ix_wishlist_items_tenant_id_wishlist_id', 'wishlist_items', ['tenant_id', 'wishlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wishlist_items_tenant_id_wishlist_id', table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index('uq_wishlists_one_per_customer', table_name='wishlists')
    op.drop_table('wishlists')
    # ### end Alembic commands ###
