"""checkout idempotency key

Revision ID: 5f254952561c
Revises: 27009d937698
Create Date: 2026-09-05 16:01:00.786413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f254952561c'
down_revision: Union[str, Sequence[str], None] = '27009d937698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=80), nullable=True))
    op.create_unique_constraint('uq_orders_tenant_customer_idempotency', 'orders', ['tenant_id', 'customer_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_tenant_customer_idempotency', 'orders', type_='unique')
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###
