"""review moderation, soft delete, aggregates

Revision ID: 670d5eb85560
Revises: 9b5a7ba86a3d
Create Date: 2026-09-02 06:11:28.200691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670d5eb85560'
down_revision: Union[str, Sequence[str], None] = '9b5a7ba86a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_rating_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('rating_1_count', sa.Integer(), nullable=False),
    sa.Column('rating_2_count', sa.Integer(), nullable=False),
    sa.Column('rating_3_count', sa.Integer(), nullable=False),
    sa.Column('rating_4_count', sa.Integer(), nullable=False),
    sa.Column('rating_5_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_product_rating_summaries_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_rating_summaries')),
    sa.UniqueConstraint('tenant_id', 'product_id', name='uq_product_rating_summaries_tenant_product')
    )
    op.create_index(op.f('ix_product_rating_summaries_product_id'), 'product_rating_summaries', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_rating_summaries_tenant_id'), 'product_rating_summaries', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_review_images_one_per_review', 'review_images', ['tenant_id', 'review_id'])
    op.add_column('reviews', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint(op.f('uq_tenant_user_product_review'), 'reviews', type_='unique')
    op.create_index('uq_tenant_user_product_review', 'reviews', ['tenant_id', 'user_id', 'product_id'], unique=True, postgresql_where=sa.text('NOT is_deleted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tenant_user_product_review', table_name='reviews', postgresql_where=sa.text('NOT is_deleted'))
    op.create_unique_constraint(op.f('uq_tenant_user_product_review'), 'reviews', ['tenant_id', 'user_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('reviews', 'is_deleted')
    op.drop_constraint('uq_review_images_one_per_review', 'review_images', type_='unique')
    op.drop_index(op.f('ix_product_rating_summaries_tenant_id'), table_name='product_rating_summaries')
    op.drop_index(op.f('ix_product_rating_summaries_product_id'), table_name='product_rating_summaries')
    op.drop_table('product_rating_summaries')
    # ### end Alembic commands ###
