"""align coupons schema with its models

Revision ID: 8cb4b3a96b1f
Revises: 0e00dd896659
Create Date: 2026-09-05 04:25:05.201668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb4b3a96b1f'
down_revision: Union[str, Sequence[str], None] = '0e00dd896659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The composite key on coupons has to exist before anything can reference it.
    op.create_unique_constraint('uq_coupons_tenant_id_id', 'coupons', ['tenant_id', 'id'])
    op.create_index('ix_coupons_tenant_id_created_at', 'coupons', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_coupon_usages_tenant_id_coupon_id_customer_id', 'coupon_usages', ['tenant_id', 'coupon_id', 'customer_id'], unique=False)
    op.drop_constraint(op.f('fk_coupon_usages_coupon_id_coupons'), 'coupon_usages', type_='foreignkey')
    op.create_foreign_key('fk_coupon_usages_tenant_coupon_coupons', 'coupon_usages', 'coupons', ['tenant_id', 'coupon_id'], ['tenant_id', 'id'], ondelete='RESTRICT')
    op.create_check_constraint(op.f('ck_coupons_coupon_code_uppercase'), 'coupons', 'code=upper(code)')
    op.create_check_constraint(op.f('ck_coupons_starts_before_expires'), 'coupons', 'starts_at IS NULL OR expires_at IS NULL OR starts_at < expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Mirror of the upgrade: the referencing key goes before the key it needs.
    op.drop_constraint('fk_coupon_usages_tenant_coupon_coupons', 'coupon_usages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_coupon_usages_coupon_id_coupons'), 'coupon_usages', 'coupons', ['coupon_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_coupon_usages_tenant_id_coupon_id_customer_id', table_name='coupon_usages')
    op.drop_index('ix_coupons_tenant_id_created_at', table_name='coupons')
    op.drop_constraint('uq_coupons_tenant_id_id', 'coupons', type_='unique')
    op.drop_constraint(op.f('ck_coupons_starts_before_expires'), 'coupons', type_='check')
    op.drop_constraint(op.f('ck_coupons_coupon_code_uppercase'), 'coupons', type_='check')
    # ### end Alembic commands ###
