"""add coupon fields to orders

Revision ID: 957a306ffa94
Revises: 346e90ad9f8c
Create Date: 2026-09-03 11:09:35.981153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957a306ffa94'
down_revision: Union[str, Sequence[str], None] = '346e90ad9f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('coupon_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.create_foreign_key(op.f('fk_orders_coupon_id_coupons'), 'orders', 'coupons', ['coupon_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('ck_orders_total_is_subtotal_plus_shipping_plus_tax'), 'orders', type_='check')
    op.create_check_constraint(op.f('ck_orders_discount_not_more_than_subtotal'), 'orders', 'discount_amount <= subtotal')
    op.create_check_constraint(op.f('ck_orders_discount_not_negative'), 'orders', 'discount_amount >= 0')
    op.create_check_constraint(op.f('ck_orders_total_matches_components'), 'orders', 'total_amount = subtotal - discount_amount + shipping_amount + tax_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_orders_total_matches_components'), 'orders', type_='check')
    op.drop_constraint(op.f('ck_orders_discount_not_negative'), 'orders', type_='check')
    op.drop_constraint(op.f('ck_orders_discount_not_more_than_subtotal'), 'orders', type_='check')
    op.create_check_constraint(op.f('ck_orders_total_is_subtotal_plus_shipping_plus_tax'), 'orders', 'total_amount = (subtotal + shipping_amount + tax_amount)')
    op.drop_constraint(op.f('fk_orders_coupon_id_coupons'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'coupon_id')
    # ### end Alembic commands ###
