"""rework reviews schema with tenant scoped uuid pks

Revision ID: 9b5a7ba86a3d
Revises: ab0d0b8ddb5b
Create Date: 2026-08-31 16:10:38.153048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5a7ba86a3d'
down_revision: Union[str, Sequence[str], None] = 'ab0d0b8ddb5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_images', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('fk_review_images_review_id_reviews'), 'review_images', type_='foreignkey')
    op.execute('ALTER TABLE review_images ALTER COLUMN id DROP DEFAULT')
    op.alter_column('review_images', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='gen_random_uuid()')
    op.alter_column('review_images', 'review_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='gen_random_uuid()')
    op.drop_index(op.f('ix_review_images_id'), table_name='review_images')
    op.drop_index(op.f('ix_review_images_review_id'), table_name='review_images')
    op.create_index('ix_review_images_tenant_id_review_id', 'review_images', ['tenant_id', 'review_id'], unique=False)
    op.create_unique_constraint('uq_review_images_tenant_id_id', 'review_images', ['tenant_id', 'id'])
    op.create_foreign_key(op.f('fk_review_images_tenant_id_tenants'), 'review_images', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.execute('ALTER TABLE reviews ALTER COLUMN id DROP DEFAULT')
    op.alter_column('reviews', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='gen_random_uuid()')
    op.alter_column('reviews', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_constraint(op.f('uq_user_product_review'), 'reviews', type_='unique')
    op.create_index('ix_reviews_tenant_id_product_id', 'reviews', ['tenant_id', 'product_id'], unique=False)
    op.create_index('ix_reviews_tenant_id_user_id', 'reviews', ['tenant_id', 'user_id'], unique=False)
    op.create_unique_constraint('uq_reviews_tenant_id_id', 'reviews', ['tenant_id', 'id'])
    op.create_unique_constraint('uq_tenant_user_product_review', 'reviews', ['tenant_id', 'user_id', 'product_id'])
    op.drop_constraint(op.f('fk_reviews_tenant_product_products'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_tenant_user_users'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_tenant_product_products', 'reviews', 'products', ['tenant_id', 'product_id'], ['tenant_id', 'id'], ondelete='SET NULL')
    op.create_foreign_key('fk_reviews_tenant_user_users', 'reviews', 'users', ['tenant_id', 'user_id'], ['tenant_id', 'id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_reviews_tenant_id_tenants'), 'reviews', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_review_images_tenant_review_reviews', 'review_images', 'reviews', ['tenant_id', 'review_id'], ['tenant_id', 'id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # -- drop constraints that depend on the tenant-scoped columns/indexes below --
    op.drop_constraint(op.f('fk_review_images_tenant_id_tenants'), 'review_images', type_='foreignkey')
    op.drop_constraint('fk_review_images_tenant_review_reviews', 'review_images', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_tenant_id_tenants'), 'reviews', type_='foreignkey')
    op.drop_constraint('fk_reviews_tenant_user_users', 'reviews', type_='foreignkey')
    op.drop_constraint('fk_reviews_tenant_product_products', 'reviews', type_='foreignkey')

    op.drop_constraint('uq_review_images_tenant_id_id', 'review_images', type_='unique')
    op.drop_index('ix_review_images_tenant_id_review_id', table_name='review_images')
    op.drop_constraint('uq_tenant_user_product_review', 'reviews', type_='unique')
    op.drop_constraint('uq_reviews_tenant_id_id', 'reviews', type_='unique')
    op.drop_index('ix_reviews_tenant_id_user_id', table_name='reviews')
    op.drop_index('ix_reviews_tenant_id_product_id', table_name='reviews')

    # -- column type/nullability reversions --
    op.alter_column('reviews', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reviews', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reviews', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='0')
    op.alter_column('review_images', 'review_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='0')
    op.alter_column('review_images', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='0')
    op.drop_column('review_images', 'tenant_id')

    # -- restore old indexes/constraints --
    op.create_unique_constraint(op.f('uq_user_product_review'), 'reviews', ['user_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_review_images_review_id'), 'review_images', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_images_id'), 'review_images', ['id'], unique=False)

    # -- restore old foreign keys --
    op.create_foreign_key(op.f('fk_reviews_tenant_user_users'), 'reviews', 'users', ['tenant_id', 'user_id'], ['tenant_id', 'id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_reviews_tenant_product_products'), 'reviews', 'products', ['tenant_id', 'product_id'], ['tenant_id', 'id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_review_images_review_id_reviews'), 'review_images', 'reviews', ['review_id'], ['id'], ondelete='CASCADE')
