"""payments

What is owed on an order and whether it has been collected. Everything is cash
on delivery, so a payment sits at PENDING from the moment the customer chooses
it until the order is delivered. An order can hold several payments over its
life -- a cancelled one ends FAILED -- but only one may ever be PAID, which the
partial unique index below enforces.

Revision ID: 9bed72e186eb
Revises: e67427b47903
Create Date: 2026-08-28 19:34:00.491828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bed72e186eb'
down_revision: Union[str, Sequence[str], None] = 'e67427b47903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('COD')", name=op.f('ck_payments_provider_valid')),
    sa.CheckConstraint("status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED')", name=op.f('ck_payments_status_valid')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payments_amount_not_negative')),
    sa.ForeignKeyConstraint(['tenant_id', 'order_id'], ['orders.tenant_id', 'orders.id'], name='fk_payments_tenant_order_orders', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_payments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_payments_tenant_id_id')
    )
    op.create_index('ix_payments_tenant_id_order_id', 'payments', ['tenant_id', 'order_id'], unique=False)
    op.create_index('ix_payments_tenant_id_status', 'payments', ['tenant_id', 'status'], unique=False)
    # "An order is paid once" lives in the database rather than in Python, so
    # two deliveries recorded together cannot both collect the cash.
    op.create_index('uq_payments_one_paid_per_order', 'payments', ['tenant_id', 'order_id'], unique=True, postgresql_where=sa.text("status = 'PAID'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_payments_one_paid_per_order', table_name='payments', postgresql_where=sa.text("status = 'PAID'"))
    op.drop_index('ix_payments_tenant_id_status', table_name='payments')
    op.drop_index('ix_payments_tenant_id_order_id', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
