"""tenant currency

What a storefront prices and collects in. Zeen sells in India, so INR -- which
is also the server default, so every tenant that already exists gets it without
a backfill step.

Revision ID: a46fa272fa9b
Revises: 9bed72e186eb
Create Date: 2026-08-28 20:07:06.192759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46fa272fa9b'
down_revision: Union[str, Sequence[str], None] = '9bed72e186eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False))
    op.create_check_constraint(op.f('ck_tenants_currency_is_iso_4217'), 'tenants', 'currency = upper(currency) AND length(currency) = 3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_tenants_currency_is_iso_4217'), 'tenants', type_='check')
    op.drop_column('tenants', 'currency')
    # ### end Alembic commands ###
