"""cart and cart items

Revision ID: ad224af6f974
Revises: f64c2cf40101
Create Date: 2026-08-21 21:43:42.556229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad224af6f974'
down_revision: Union[str, Sequence[str], None] = 'f64c2cf40101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # carts keys a composite foreign key on users(tenant_id, id), so that
    # constraint has to exist before the table that references it.
    op.create_unique_constraint('uq_users_tenant_id_id', 'users', ['tenant_id', 'id'])

    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'CONVERTED')", name=op.f('ck_carts_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id', 'customer_id'], ['users.tenant_id', 'users.id'], name='fk_carts_tenant_customer_users', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_carts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_carts_tenant_id_id')
    )
    op.create_index('uq_carts_one_active_per_customer', 'carts', ['tenant_id', 'customer_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_cart_items_quantity_positive')),
    sa.ForeignKeyConstraint(['tenant_id', 'cart_id'], ['carts.tenant_id', 'carts.id'], name='fk_cart_items_tenant_cart_carts', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'variant_id'], ['product_variants.tenant_id', 'product_variants.id'], name='fk_cart_items_tenant_variant_product_variants', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_cart_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items')),
    sa.UniqueConstraint('cart_id', 'variant_id', name='uq_cart_items_cart_variant')
    )
    op.create_index('ix_cart_items_tenant_id_cart_id', 'cart_items', ['tenant_id', 'cart_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cart_items_tenant_id_cart_id', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index('uq_carts_one_active_per_customer', table_name='carts', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('carts')

    # Last: the composite foreign key above depended on this constraint.
    op.drop_constraint('uq_users_tenant_id_id', 'users', type_='unique')
    # ### end Alembic commands ###
