"""enforce tenant user email uniqueness

Revision ID: d0721ebac024
Revises: a2c1c42eefa3
Create Date: 2026-08-13 15:04:11.847100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0721ebac024'
down_revision: Union[str, Sequence[str], None] = 'a2c1c42eefa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_tenant_email', 'users', ['tenant_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_tenant_email', 'users', type_='unique')
    # ### end Alembic commands ###
