"""addresses, orders and order items

Revision ID: e67427b47903
Revises: ad224af6f974
Create Date: 2026-08-25 18:49:08.328616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67427b47903'
down_revision: Union[str, Sequence[str], None] = 'ad224af6f974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Customer-facing order numbers (ORD-100001, ORD-100002, ...). A sequence
    # rather than a counter in application code, so concurrent checkouts can
    # never be handed the same number. Alembic does not autogenerate standalone
    # sequences, so it is written out here by hand.
    op.execute("CREATE SEQUENCE IF NOT EXISTS order_number_seq START WITH 100001")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("phone ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f('ck_addresses_phone_is_e164')),
    sa.CheckConstraint('length(trim(address_line_1)) > 0', name=op.f('ck_addresses_address_line_1_not_blank')),
    sa.CheckConstraint('length(trim(city)) > 0', name=op.f('ck_addresses_city_not_blank')),
    sa.CheckConstraint('length(trim(full_name)) > 0', name=op.f('ck_addresses_full_name_not_blank')),
    sa.CheckConstraint('length(trim(postal_code)) > 0', name=op.f('ck_addresses_postal_code_not_blank')),
    sa.ForeignKeyConstraint(['tenant_id', 'customer_id'], ['users.tenant_id', 'users.id'], name='fk_addresses_tenant_customer_users', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_addresses_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_addresses_tenant_id_id')
    )
    op.create_index('ix_addresses_tenant_id_customer_id', 'addresses', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('uq_addresses_one_default_per_customer', 'addresses', ['tenant_id', 'customer_id'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_name', sa.String(length=150), nullable=False),
    sa.Column('delivery_phone', sa.String(length=16), nullable=False),
    sa.Column('delivery_address_line_1', sa.String(length=255), nullable=False),
    sa.Column('delivery_address_line_2', sa.String(length=255), nullable=True),
    sa.Column('delivery_city', sa.String(length=100), nullable=False),
    sa.Column('delivery_state', sa.String(length=100), nullable=False),
    sa.Column('delivery_postal_code', sa.String(length=20), nullable=False),
    sa.Column('delivery_country', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED')", name=op.f('ck_orders_payment_status_valid')),
    sa.CheckConstraint("status IN ('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')", name=op.f('ck_orders_status_valid')),
    sa.CheckConstraint('shipping_amount >= 0', name=op.f('ck_orders_shipping_not_negative')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_orders_subtotal_not_negative')),
    sa.CheckConstraint('total_amount = subtotal + shipping_amount', name=op.f('ck_orders_total_is_subtotal_plus_shipping')),
    sa.ForeignKeyConstraint(['tenant_id', 'customer_id'], ['users.tenant_id', 'users.id'], name='fk_orders_tenant_customer_users', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_orders_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_number', name='uq_orders_order_number'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_orders_tenant_id_id')
    )
    op.create_index('ix_orders_tenant_id_customer_id', 'orders', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_orders_tenant_id_payment_status', 'orders', ['tenant_id', 'payment_status'], unique=False)
    op.create_index('ix_orders_tenant_id_status', 'orders', ['tenant_id', 'status'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('variant_name', sa.String(length=150), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.CheckConstraint('subtotal = unit_price * quantity', name=op.f('ck_order_items_subtotal_is_price_times_quantity')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_order_items_unit_price_not_negative')),
    sa.ForeignKeyConstraint(['tenant_id', 'order_id'], ['orders.tenant_id', 'orders.id'], name='fk_order_items_tenant_order_orders', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'product_id'], ['products.tenant_id', 'products.id'], name='fk_order_items_tenant_product_products', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'variant_id'], ['product_variants.tenant_id', 'product_variants.id'], name='fk_order_items_tenant_variant_product_variants', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_order_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    sa.UniqueConstraint('order_id', 'variant_id', name='uq_order_items_order_variant')
    )
    op.create_index('ix_order_items_tenant_id_order_id', 'order_items', ['tenant_id', 'order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_tenant_id_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_orders_tenant_id_status', table_name='orders')
    op.drop_index('ix_orders_tenant_id_payment_status', table_name='orders')
    op.drop_index('ix_orders_tenant_id_customer_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('uq_addresses_one_default_per_customer', table_name='addresses', postgresql_where=sa.text('is_default'))
    op.drop_index('ix_addresses_tenant_id_customer_id', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###

    op.execute("DROP SEQUENCE IF EXISTS order_number_seq")
